services:
    postgresql:
        image: postgres
        restart: unless-stopped
        ports:
            - '15432:5432'
        environment:
            POSTGRES_USER: auth
            POSTGRES_PASSWORD: auth
            POSTGRES_DB: auth
